name: Deploy Streamlit app

on:
  workflow_dispatch:
      branches:
      - main
jobs:
  build-push-deploy:
    name: Build Docker image, push to repository, pull from server and run
    runs-on: ubuntu-latest

    steps:
    # Part 1: Rebuilding the container image on DockerHub
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/arm64/v8, linux/x86_64
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/app:latest

      # Part 2: Deploying the container image to the VPS
      - name: copy files to target server via scp
        # Copy docker-compose files to target server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          source: "./docker-compose.yml" #pass list of files from repo. e.g. "./file1.ext,./file2.ext"
          target: "~/${{ github.event.repository.name }}/"

      - name: executing remote ssh commands using ssh key
        # Action to ssh into the VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.KEY }}
         passphrase: ${{ secrets.SSH_PASSPHRASE }}
         port: 22
         script: |
          # Login to Docker Hub
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          # Pull down the container image from Docker Hub
          docker pull  ${{ secrets.DOCKERHUB_USERNAME }}/app:latest
          # open folder with docker-compose.yml file
          cd ${{ github.event.repository.name }}
          # update and run containers
          docker compose up --detach
